[webdl-anime]
profile-desc=WEB-DL Anime (release groups)
profile-cond=string.match(p.filename, "HatSubs")~=nil or string.match(p.filename, "SubsPlease")~=nil or string.match(p.filename, "HorribleSubs")~=nil or string.match(p.filename, "Erai%-raws")~=nil or string.match(p.filename, "Yameii")~=nil or string.match(p.filename, "VARYG")~=nil or string.match(p.filename, "%[Web%-DL%]")~=nil 
profile-restore=copy-equal
sub-ass-override=force
deband=yes

[webdl-generic]
profile-desc=Generic Web-DL
profile-cond=string.match(p.filename, "%[Web%-DL%]")~=nil
profile-restore=copy-equal
deband=yes

[low-bitrate]
profile-desc=Enable debanding for compressed sources
profile-cond=get("video-params/average-bpp") < 24
profile-restore=copy
deband=yes

[extension.gif]
profile-desc=Loop GIF playback infinitely
loop-file=inf

[image-loop]
profile-cond=path:lower():match("%.gif$") or path:lower():match("%.png$") or path:lower():match("%.jpe?g$") or path:lower():match("%.webp$")
loop-file=inf

[http]
profile-cond=path and path:match("^https?://")
title=${metadata/by-key/title:${filename/no-ext}}

# [high-upscale]
# profile-desc=Enable ArtCNN upscale for scaled video
# profile-cond=osd_width / width >= 2.0
# profile-restore=copy
# glsl-shaders=~~/shaders/CfL_Prediction.glsl;~~/shaders/ArtCNN_C4F32.glsl
