monospace_font=JetBrains Mono
font_size=15
background_alpha=0
padding=16
corner_radius=4






# === Console Keybindings ===
# TAB        : Autocomplete command / argument
# Ctrl+I     : Cycle autocomplete suggestions (forward)
# Shift+TAB  : Cycle autocomplete suggestions (reverse)
# ↑ (Up)     : Navigate command history (previous)
# ↓ (Down)   : Navigate command history (next)
# Enter      : Execute selected / typed command
