# deband-cycle.conf
# https://github.com/Xightify/mpv-config

# Keybind to cycle deband profiles. Leave blank to disable.
cycle_key=Shift+F7

# How long deband profile OSD messages stay visible, in seconds.
osd_message_duration=0.5
