# subtitle.conf
# https://github.com/Xightify/mpv-config

# Keybind to cycle subtitle styles. Leave blank to disable.
cycle_key=Alt+F7

# How long subtitle style OSD messages stay visible, in seconds.
osd_message_duration=0.5
